dist: xenial
sudo: false
language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.3
env:
  - MIX_ENV=test
  - MIX_ENV=test ELIXIR_ERL_OPTIONS="+T 9"
before_script:
  - mix compile --warnings-as-errors
script:
  - mix test